name: Publish to Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Kodi to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: xayon/docker-kodi-beta
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache: true

