name: Publish to Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Kodi to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: xayon/docker-kodi-beta
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache: true
        tags: latest,x11

  build_gbm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Kodi to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        env:
          FLAGS: "-DCORE_PLATFORM_NAME=gbm -DGBM_RENDER_SYSTEM=gl"
        name: xayon/docker-kodi-beta
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache: true
        dockerfile: Dockerfile.gbm
        tags: gbm
        buildargs: FLAGS

  build_gbm_gles:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Kodi to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        env:
          FLAGS: "-DCORE_PLATFORM_NAME=gbm -DGBM_RENDER_SYSTEM=gles"
        name: xayon/docker-kodi-beta
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache: true
        dockerfile: Dockerfile.gbm_gles
        tags: gbmgles
